name: Crowdin Extract

on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '30 */2 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.4']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Generate configuration
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php app.php setup

      - name: Extract translations
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php app.php meta:extractExtensions
          php app.php extract:core

      - name: Extract status
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php app.php meta:status.export
          php app.php management:status

      - name: Copy files to translation server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: ${{ secrets.SCP_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "export/rsync"
          target: "/home/localize/www/export_v2/"

