name: Crowdin Extract

on:
  workflow_dispatch:
  push:
    branches:
      - v3
  schedule:
    - cron:  '30 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install dependencies
        run: |
            cp .env.ci .env
            composer install --no-progress

      - name: Generate configuration
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
            ./bin/crowdinSetup

      - name: Extract translations
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:extract:extension
          php ./bin/console app:extract:core

      - name: Extract status
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:status:project
          php ./bin/console app:status:overview

      - name: Copy files to translation server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: ${{ secrets.SCP_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "export/rsync"
          target: "/home/localize/www/export_v3/"

