name: Crowdin Build

on:
#  push:
#  schedule:
#    - cron:  '0 */2 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.4']
    steps:
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Get configuration
        run: |
          wget ${{ secrets.CONFIGURATION_URL }}

      - name: Build all projects
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: php app.php crowdin:meta:build
