name: Crowdin Extract

on:
#  push:
#  schedule:
#    - cron:  '30 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.4']
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Get configuration
        run: |
          wget ${{ secrets.CONFIGURATION_URL }}

      - name: Extract translations
        run: |
          php app.php crowdin:meta:extractExt
          php app.php crowdin:extract:core '*'

      - name: Extract status
        run: |
          php app.php crowdin:meta:status.export
          php app.php crowdin:management:status --export=1

      - name: Cleanup
        run: rm -rf configuration.json

      - name: Copy files to translation server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SCP_HOST }}
          USERNAME: ${{ secrets.SCP_USERNAME }}
          PORT: ${{ secrets.SCP_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "/home/runner/work/crowdin-bridge/crowdin-bridge/public/rsync"
          target: "/home/localize/www/export/"

