name: Crowdin Build

on:
  workflow_dispatch:
  push:
    branches:
      - v3
  schedule:
    - cron:  '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install dependencies
        run: |
            cp .env.ci .env
            composer install --no-progress

      - name: Generate configuration
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:setup

#      - name: Build all projects
#        env:
#          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
#        run: ./bin/console app:build
