name: Extract

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: '8.5'
          tools: composer:v2

      - name: Install dependencies
        run: |
            cp .env.ci .env
            composer install --no-progress --no-dev

      - name: Generate configuration
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
            ./bin/crowdinSetup

      - name: Build all projects
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:build -v

      - name: Extract translations
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:extract:extension
          php ./bin/console app:extract:core

      - name: Extract status
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
        run: |
          php ./bin/console app:status:project -v
          php ./bin/console app:status:overview -v

      - name: Copy files to translation server
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: ${{ secrets.SCP_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "export/rsync"
          target: "/home/localize/www/export_v3/"

